### ISSUE TITLE
Implement particle simulation.

### ISSUE THREAD

**Issue by koneil18** [koneil18/FinalProject-Graphics#7]
• Ray Tracing
• Photon Mapping
• Particle Simulation (incorporated in a nice, natural way)
• Cloth simulation (bonus points)
• Shallow fluid simulation
• Volumetric fluid simulation (bonus points)

**Comment by GarySeip** [comment]
To-Do:

- [ ] Talk with Stuetzle about particle simulation.
- [ ] Create dust particles.
- [ ] Figure out how to implement force field.
- [ ] Implement force field.
- [ ] Makes force field interact with dust particles.
- [ ] Minimize lag/optimize performance.
- [ ] Have dust bounce off of objects.
- [ ] (Stretch) Have dust come to rest on board, objects.
- [ ] (Stretch) Have dust be affected by checker movement.
- [ ] (Stretch) Have dust be affected by board movement if applicable.
